contentdirectory = "/home/alex/.gladius/content"
contentport = "8080"
disableautojoin = false
disableheartbeat = false
gladiusbase = "/home/alex/.gladius"
loglevel = "info"
networkgatewayhostname = "localhost"
networkgatewayport = "3001"
networkgatewayprotocol = "http"
overrideip = ""
p2pseednodeaddress = "165.227.16.209"
p2pseednodeport = "7947"
